In [9]:
import pandas as pd

In [10]:
dataset = "data/reviews.csv"

In [11]:
dataset = pd.read_csv(dataset)
dataset.head(3)

,id,asin,url,body,date,title,images,videos,stars,user_id,variation,found_helpful,verified_purchase
0,RVAV3SWVU0O0W,B085DVHQ57,https://www.amazon.com/gp/customer-reviews/RVA...,Whenever asked by recent high school grads wha...,Sat Jul 05 2025,"My go-to water bottle, I take it everywhere I go",[],[],5,amzn1.account.AEPH7VYTQBYH6UW7INYUMMYNSBEA,Size: 24 Ounces Color: Shy Marshmallow,5,1.0
1,R1VVZ8F6WC4CWP,B085DVHQ57,https://www.amazon.com/gp/customer-reviews/R1V...,I bought the Owala FreeSip Insulated Stainless...,Fri Jun 06 2025,Perfect for Kids and Adults — My 12-Year-Old L...,[],[],5,amzn1.account.AE3WFQSNFH7ARSXPHUQZQV6CQ2TA,Size: 24 Ounces Color: Shy Marshmallow,47,1.0
2,R1N1YR132OT1B4,B085DVHQ57,https://www.amazon.com/gp/customer-reviews/R1N...,Can't say enough about this water bottle. I tr...,Thu Jun 26 2025,Not Even Close - Best H20 Bottle on the Market,[],[],5,amzn1.account.AE2PKPB3WT4L6WKMFUQHMA5ZMD3A,Size: 32 Ounces Color: Foggy Tide,25,1.0

In [12]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 255966 entries, 0 to 255965
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 255966 non-null  str
 1   asin               255966 non-null  str
 2   url                255966 non-null  str
 3   body               255714 non-null  str
 4   date               255966 non-null  str
 5   title              254572 non-null  str
 6   images             255966 non-null  str
 7   videos             255966 non-null  str
 8   stars              255966 non-null  int64
 9   user_id            254633 non-null  str
 10  variation          212689 non-null  str
 11  found_helpful      255966 non-null  int64
 12  verified_purchase  253543 non-null  float64
dtypes: float64(1), int64(2), str(10)
memory usage: 136.7 MB

Right off the bat some of these won't be helpful. we can eliminate them entirely and decrease our storage and memory usage

In [13]:
dataset.describe()

               stars  found_helpful  verified_purchase
count  255966.000000  255966.000000           253543.0
mean        4.642484       4.666260                1.0
std         0.743020     121.531447                0.0
min         1.000000       0.000000                1.0
25%         5.000000       0.000000                1.0
50%         5.000000       0.000000                1.0
75%         5.000000       1.000000                1.0
max         5.000000   30351.000000                1.0

In [14]:
dataset.columns.to_list()

['id',
 'asin',
 'url',
 'body',
 'date',
 'title',
 'images',
 'videos',
 'stars',
 'user_id',
 'variation',
 'found_helpful',
 'verified_purchase']

In [15]:
columns_to_delete = ["url","images","videos", "user_id",]
dataset = dataset.drop(columns=columns_to_delete)

In [16]:
dataset.head(10)

,id,asin,body,date,title,stars,variation,found_helpful,verified_purchase
0,RVAV3SWVU0O0W,B085DVHQ57,Whenever asked by recent high school grads wha...,Sat Jul 05 2025,"My go-to water bottle, I take it everywhere I go",5,Size: 24 Ounces Color: Shy Marshmallow,5,1.0
1,R1VVZ8F6WC4CWP,B085DVHQ57,I bought the Owala FreeSip Insulated Stainless...,Fri Jun 06 2025,Perfect for Kids and Adults — My 12-Year-Old L...,5,Size: 24 Ounces Color: Shy Marshmallow,47,1.0
2,R1N1YR132OT1B4,B085DVHQ57,Can't say enough about this water bottle. I tr...,Thu Jun 26 2025,Not Even Close - Best H20 Bottle on the Market,5,Size: 32 Ounces Color: Foggy Tide,25,1.0
3,R2NVM73BPETXF8,B085DVHQ57,I've had this for over a year now and it's def...,Fri Jun 13 2025,Best water bottle,5,Size: 24 Ounces Color: Foggy Tide,16,1.0
4,R20Q2RHQ3NGXB,B085DVHQ57,This is our third Owala Kids FreeSip bottle an...,Tue Jul 01 2025,"Great water bottle, easy clean",5,Size: 16 Ounces Color: Mint Chocolate,3,1.0
5,RGUUD0NOL8VR,B085DVHQ57,"I SUCK at drinking water. I always have, but f...",Thu Jun 26 2025,LOVE LOVE LOVE!,5,Size: 24 Ounces Color: Shy Marshmallow,4,1.0
6,R2ET9Y6FJZ7NPL,B085DVHQ57,My wife and I have been using this bottle for ...,Wed Jun 25 2025,Keeps drinks cold and looks great – Just a bit...,4,Size: 24 Ounces Color: Iced Breeze,12,1.0
7,RIOYSHKYZT6KE,B085DVHQ57,I absolutely love this Owala FreeSip water bot...,Wed Jul 02 2025,My favorite water bottle – keeps water cold & ...,5,Size: 32 Ounces Color: Denim,3,1.0
8,R3E1VSVOHRHVCY,B085DVHQ57,"32oz. Photos for size comparison, next to my 3...",Sun Jun 08 2025,Fantastic,5,Size: 32 Ounces Color: Foggy Tide,29,1.0
9,R2NDLMKP5C9O7Q,B085DVHQ57,You truly know how good something is when you ...,Fri Jun 27 2025,You'll MIss it When You Forget It,5,Size: 24 Ounces Color: Boneyard,2,1.0

In [17]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 255966 entries, 0 to 255965
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 255966 non-null  str
 1   asin               255966 non-null  str
 2   body               255714 non-null  str
 3   date               255966 non-null  str
 4   title              254572 non-null  str
 5   stars              255966 non-null  int64
 6   variation          212689 non-null  str
 7   found_helpful      255966 non-null  int64
 8   verified_purchase  253543 non-null  float64
dtypes: float64(1), int64(2), str(6)
memory usage: 103.3 MB